### ISSUE TITLE
Brightness Keys

### ISSUE THREAD

**Issue by daviddean-x** [3ig/IdeaPad-S540-15IML-hackintosh#3]
Will your brightness keys work? For me none but over prefpane.

**Comment by daviddean-x** [comment]
Solved by use this created patch:

into method label _Q8F replace_content
begin
// Brightness Down\n
Notify(PS2K, 0x0205)\n
Notify(PS2K, 0x0285)\n
end;
into method label _Q8E replace_content
begin
// Brightness Up\n
Notify(PS2K, 0x0206)\n
Notify(PS2K, 0x0286)\n
end;

https://www.insanelymac.com/forum/topic/305030-guide-how-to-fix-brightness-hotkeys-in-dsdt/

**Comment by 3ig** [comment]
Half a year later i still can't make a separate file to fix this (it's the only thing left) :) The only way this works is using the above patch in DSTD.dsl, but obviously not optimal.
This should be really simple and straightforward, but i have no idea why the code below doesn't work :D

```
DefinitionBlock ("", "SSDT", 2, "ACDT", "BrightFN", 0x00000000)
{
    External (_SB_.PCI0.LPCB.H_EC, DeviceObj)
    External (_SB_.PCI0.LPCB.PS2K, DeviceObj)

    Scope (_SB.PCI0.LPCB.H_EC)
    {
        Method (_Q8E, 0, NotSerialized)  // Brightness Up
        {
            Notify (\_SB.PCI0.LPCB.PS2K, 0x0206)
            Notify (\_SB.PCI0.LPCB.PS2K, 0x0286) 
        }
        
        Method (_Q8F, 0, NotSerialized)  // Brightness Down
        {
            Notify (\_SB.PCI0.LPCB.PS2K, 0x0205)
            Notify (\_SB.PCI0.LPCB.PS2K, 0x0285)
        }
    }
} 
```

**Comment by marianopela** [comment]
@3ig It has a relation to SSDT-XOSI. Do you have it?

**Comment by 3ig** [comment]
> @3ig It has a relation to SSDT-XOSI. Do you have it?

I know ... it's there. If i replace the Notify directly in the DSTD it works. I can't make it work in a separate SSDT.
